version: "3"

services:

  bioformats2raw:
    build: bioformats2raw
    entrypoint:
      - "/src/script.sh"
    volumes:
      - ".:/src"
      - "/uod/idr/filesets:/uod/idr/filesets:ro"
      - "/uod/idr-scratch/josh-n5:/out"
